/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui.wecare;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sreyoshi Ghosh
 */
public class EmployeeLoginFrame extends javax.swing.JFrame {

// performance improvement by reducing DB call
    public static String Emp_name = "";
    public static String Emp_org = "";
    Connection conn;

    public EmployeeLoginFrame() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(250, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Employee Login");

        jLabel2.setText("User Name");

        jLabel3.setText("Password");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //login button
        //Connection con=null;
        Statement st = null;
        ResultSet rs = null;

//        try {
//            con = DriverManager.getConnection(
//                "jdbc:oracle:thin:@localhost:1521:xe","system","admin");
//        } catch (SQLException ex) {
//
//        }
        try {
            String url = "jdbc:oracle:thin:@10.0.0.107:1521:xe";
            String user = "SYSTEM";
            String password = "trisha";
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection(url, user, password);
        } catch (Exception e) {
        }

        //create the statement object
        String user = jTextField1.getText();
        Emp_name = user;
        String pass = jPasswordField1.getText();

        jTextField1.setText("");
        jPasswordField1.setText("");

        //String s = String.format("select * from enterprise_detail ed,enterprise e where ed.username='%s' and ed.password='%s' and e.type='NGO' and e.name=ed.username", user, pass);
        String s = String.format("select * from work_area a where a.username='%s' and a.password='%s' and a.ORGANIZATION='NGO'", user, pass);

        
        try {
            st = conn.createStatement();
            rs = st.executeQuery(s);  // execute query

            if (rs.next()) {
                // MainFrame. ngoPanel.setVisible(true);
                MainFrame.ngoPanel.setVisible(true);
                //MainFrame.ngoPanel.updateTableForNgo();
                setVisible(false);

            } else {
                //s = String.format("select * from enterprise_detail ed,enterprise e where ed.username='%s' and ed.password='%s' and e.type='Hospital' and e.name=ed.username", user, pass);
                s = String.format("select * from work_area a where a.username='%s' and a.password='%s' and a.ORGANIZATION='Doctor'", user, pass);

                st = conn.createStatement();
                rs = st.executeQuery(s);  // execute query

                if (rs.next()) {
                    MainFrame.nurseReading.setVisible(true);

                    setVisible(false);

                } else {

                    //s = String.format("select * from enterprise_detail ed,enterprise e where ed.username='%s' and ed.password='%s' and e.type='Police' and e.name=ed.username", user, pass);
                    s = String.format("select * from work_area a where a.username='%s' and a.password='%s' and a.ORGANIZATION='Nurse'", user, pass);

                    st = conn.createStatement();
                    rs = st.executeQuery(s);  // execute query

                    if (rs.next()) {
                        MainFrame.nurseReading.setVisible(true);
                        setVisible(false);

                    } else {

                        //s = String.format("select * from enterprise_detail ed,enterprise e where ed.username='%s' and ed.password='%s' and e.type='Police' and e.name=ed.username", user, pass);
                        s = String.format("select * from work_area a where a.username='%s' and a.password='%s' and a.ORGANIZATION='Receptionist'", user, pass);

                        st = conn.createStatement();
                        rs = st.executeQuery(s);  // execute query

                        if (rs.next()) {
                            MainFrame.reception.setVisible(true);
                            setVisible(false);

                        } else {

                            //s = String.format("select * from enterprise_detail ed,enterprise e where ed.username='%s' and ed.password='%s' and e.type='Police' and e.name=ed.username", user, pass);
                            s = String.format("select * from work_area a where a.username='%s' and a.password='%s' and a.ORGANIZATION='Pharma'", user, pass);

                            st = conn.createStatement();
                            rs = st.executeQuery(s);  // execute query

                            if (rs.next()) {
                                MainFrame.pharmacy.setVisible(true);
                                setVisible(false);

                            } else {

                                //s = String.format("select * from enterprise_detail ed,enterprise e where ed.username='%s' and ed.password='%s' and e.type='Police' and e.name=ed.username", user, pass);
                                s = String.format("select * from work_area a where a.username='%s' and a.password='%s' and a.ORGANIZATION='Examination'", user, pass);

                                st = conn.createStatement();
                                rs = st.executeQuery(s);  // execute query

                                if (rs.next()) {
                                    MainFrame.diagonasticCenter.setVisible(true);
                                    setVisible(false);

                                } else {

                                        //s = String.format("select * from enterprise_detail ed,enterprise e where ed.username='%s' and ed.password='%s' and e.type='Police' and e.name=ed.username", user, pass);
                                        s = String.format("select * from work_area a where a.username='%s' and a.password='%s' and a.ORGANIZATION='Police'", user, pass);

                                        st = conn.createStatement();
                                        rs = st.executeQuery(s);  // execute query

                                        if (rs.next()) {
                                            MainFrame.policePanel.setVisible(true);
                                            setVisible(false);

                                        } else {

                                            //s = String.format("select *from enterprise_detail ed,enterprise e where ed.username='%s' and ed.password='%s' and e.type='Judiciary' and e.name=ed.username", user, pass);
                                            s = String.format("select * from work_area a where a.username='%s' and a.password='%s' and a.ORGANIZATION='Judiciary'", user, pass);

                                            st = conn.createStatement();
                                            rs = st.executeQuery(s);  // execute query

                                            if (rs.next()) {
                                                MainFrame.lawyerPanel.setVisible(true);
                                                setVisible(false);

                                            } else {

                                                s = String.format("select * from work_area  where username='%s' and password='%s'", user, pass);

                                                st = conn.createStatement();
                                                rs = st.executeQuery(s);  // execute query

                                                if (rs.next()) {
                                                    MainFrame.ngoPanel.setVisible(true);
                                                    MainFrame.ngoPanel.updateTableForNgo();
                                                    setVisible(false);

                                                } else {
                                                    JOptionPane.showMessageDialog(null, "Invalid User name / password");
                                                    return;
                                                }

                                            }

                                        }

                                    
                                }
                            }
                        }
                    }

                }}

                conn.close();

            }catch (SQLException ex) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeLoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
