/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui.wecare;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sreyoshi Ghosh
 */
public class Panel1 extends javax.swing.JPanel {

    //manage enterprise panel
    
       Connection conn=null;
        Statement st=null;
        ResultSet rs=null;
        
        DefaultTableModel model ;
      
    public Panel1() {
        initComponents();
        if (conn == null) {
            try {
                String url = "jdbc:oracle:thin:@10.0.0.107:1521:xe";
                String user = "SYSTEM";
                String password = "trisha";
                Class.forName("oracle.jdbc.driver.OracleDriver");
                conn = DriverManager.getConnection(url, user, password);
            } catch (Exception e) {
            }
        }
        
        jComboBox1.addItem("Boston");
        jComboBox1.addItem("New Jersy");
        jComboBox1.addItem("New York");
        jComboBox1.addItem("Seattle");
        jComboBox1.addItem("Philadelphia");
        
        jComboBox2.addItem("Hospital");
        jComboBox2.addItem("NGO");
       jComboBox2.addItem("Judiciary");
       jComboBox2.addItem("Police");
        
        
        
        model = new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("Enterprise Name");
        model.addColumn("Location");
        model.addColumn("Type");
        


        
          try {
//            con = DriverManager.getConnection(
//                    "jdbc:oracle:thin:@localhost:1521:xe","system","admin");
           if (conn == null) {
                  try {
                      String url = "jdbc:oracle:thin:@10.0.0.107:1521:xe";
                      String user = "SYSTEM";
                      String password = "trisha";
                      Class.forName("oracle.jdbc.driver.OracleDriver");
                      conn = DriverManager.getConnection(url, user, password);
                  } catch (Exception e) {
                  }
              }

             st=conn.createStatement();
            
             String s= "select * from enterprise"  ;
             rs=st.executeQuery(s);  // execute query
            
             while(rs.next()){
                 
                 model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
                 
             }
           
               
               
            
        } catch (SQLException ex) {
            
        }
          
          
          
        
    }

    
      public  void change(){
           DefaultTableModel model ;
          
         model = new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("Enterprise Name");
        model.addColumn("Location");
        model.addColumn("Type");
        


        
          try {
            conn = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe","system","admin");
            
             st=conn.createStatement();
            
             String s= "select * from enterprise"  ;
             rs=st.executeQuery(s);  // execute query
            
             while(rs.next()){
                 
                 model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
                 
             }
           
               
               
            
        } catch (SQLException ex) {
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1900, 1397));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 670, 90));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Manage Enterprise");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 340, 70));

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Manage Enterprise Admin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 330, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Location");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 110, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enterprise");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 110, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 110, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Trisha\\Downloads\\login-blue-hi.png")); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 580, 530));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Trisha\\Downloads\\womenlogo.jpeg")); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //submit button
        String location=(String) jComboBox1.getSelectedItem();
        String type=(String) jComboBox2.getSelectedItem();
        String name=jTextField1.getText();
        if(name.isEmpty()){
JOptionPane.showMessageDialog(null, "Please enter Name"); return;
}
        
        try {
           
            
             st=conn.createStatement();
            
             String s=String.format("insert into enterprise values('%s','%s','%s')", name,location,type)    ;
             int n=st.executeUpdate(s);  // execute query
             if(n>0)
                 JOptionPane.showMessageDialog(null, "Record saved successfully");
             else
                 JOptionPane.showMessageDialog(null, "Record could not be added");
          
            
        } catch (SQLException ex) {
            
        }
          
        jTextField1.setText("");
        
        
        //-------------------
        
        //update the table
       updateEnterpriseTable();
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    void updateEnterpriseTable(){
        
         model = new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("Enterprise Name");
        model.addColumn("Location");
        model.addColumn("Type");
        
           //update the table
        if (jTable1.getRowCount() > 0) {
            for (int i = jTable1.getRowCount() - 1; i >=0; i--) {
                model.removeRow(i);
                }
            }

         try {
            
            
             st=conn.createStatement();
            
             String s= "select * from enterprise"  ;
             rs=st.executeQuery(s);  // execute query
            
             while(rs.next()){
                 
                 model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
                 
             }
           
               
               
            
        } catch (SQLException ex) {
            
        }
        
        
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //manage enterprise admin button
        MainFrame.p2.setVisible(true);
         MainFrame.p1.setVisible(false);
         MainFrame.p2.updateTable();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
          //manage enterprise  button
         MainFrame.p2.setVisible(false);
         MainFrame.p1.setVisible(true);
         updateEnterpriseTable();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
