/**
* Author:     Bit-by-Bit
* Subject:    INFO5100 - Application Engineer & Development 
* Purpose:   Sorority
*/
package com.ui.wecare;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sreyoshi Ghosh
 */
public class Panel2 extends javax.swing.JPanel {

    //manage enterprise admin
    Connection conn = null;
    Statement st = null;
    ResultSet rs = null;
    DefaultTableModel model;

    public Panel2() {
        initComponents();

        jComboBox1.addItem("Boston");
        jComboBox1.addItem("New Jersy");
        jComboBox1.addItem("New York");
        jComboBox1.addItem("Seattle");
        jComboBox1.addItem("Philadelphia");

        try {
//
//              con = DriverManager.getConnection(
//                    "jdbc:oracle:thin:@localhost:1521:xe","system","admin");
if(conn == (null)){
            try {
                String url = "jdbc:oracle:thin:@10.0.0.107:1521:xe";
                String user = "SYSTEM";
                String password = "trisha";
                Class.forName("oracle.jdbc.driver.OracleDriver");
                conn = DriverManager.getConnection(url, user, password);
            } catch (Exception e) {
            }}
            st = conn.createStatement();

            String s = String.format("select * from enterprise where location='" + jComboBox1.getSelectedItem() + "'");
            rs = st.executeQuery(s);  // execute query
            jComboBox2.removeAllItems();

            while (rs.next()) {

                jComboBox2.addItem(rs.getString(1));
            }

        } catch (SQLException ex) {

        }

        model = new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("Enterprise Name");
        model.addColumn("Location");
        model.addColumn("User Name");

    }

    public void updateTable() {

        model = new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("Enterprise Name");
        model.addColumn("Location");
        model.addColumn("User Name");

        if (jTable1.getRowCount() > 0) {
            for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }
        }

        try {

            st = conn.createStatement();

            String s = "select * from enterprise_detail";
            rs = st.executeQuery(s);  // execute query

            while (rs.next()) {

                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3)});

            }

        } catch (SQLException ex) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(860, 690));
        setPreferredSize(new java.awt.Dimension(1900, 1397));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Manage Enterprise Admin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 310, 70));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Manage Enterprise");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 310, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 620, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Location");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 110, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Enterprise");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("User name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 110, -1));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 106, -1));
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 106, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 106, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Trisha\\Downloads\\womenlogo.jpeg")); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Trisha\\Downloads\\login-blue-hi.png")); // NOI18N
        jLabel9.setText("jLabel3");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 580, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //submit button
        String location = (String) jComboBox1.getSelectedItem();
        String enterprise_name = (String) jComboBox2.getSelectedItem();
        String username = jTextField1.getText();
        String password = jPasswordField1.getText();

        String name = jTextField2.getText();

       if(username.isEmpty()){
JOptionPane.showMessageDialog(null, "Please enter Username"); return;
}
       if(password.isEmpty()){
JOptionPane.showMessageDialog(null, "Please enter Password"); return;
}
       if(name.isEmpty()){
JOptionPane.showMessageDialog(null, "Please enter Name"); return;
}
//String password
if(password.length() < 5){
JOptionPane.showMessageDialog(null, "Please Enter String password: Minimum Length 5, 1 special character, 1 Digit");
return;
}
if(!(password.contains("@") || password.contains("#") || password.contains("&") || password.contains("*") || password.contains("$") || password.contains("?"))){
JOptionPane.showMessageDialog(null, "Please Enter String password: Minimum Length 5, 1 special character, 1 Digit");
return;
}
if(!(password.contains("0") || password.contains("1") || password.contains("2") || password.contains("3") || password.contains("4") || password.contains("5") || password.contains("6") || password.contains("7") || password.contains("8") || password.contains("9"))){
JOptionPane.showMessageDialog(null, "Please Enter String password: Minimum Length 5, 1 special character, 1 Digit");
return;
}

        try {

            st = conn.createStatement();

            String s = String.format("insert into enterprise_detail values('%s','%s','%s','%s','%s')", enterprise_name, location, username, password, name);
            int n = st.executeUpdate(s);  // execute query
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Record saved successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Record could not be added");
            }

        } catch (SQLException ex) {

        }

        jTextField1.setText("");
        jTextField2.setText("");
        jPasswordField1.setText("");

        //-------------------
        if (jTable1.getRowCount() > 0) {
            for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }
        }

        try {

            st = conn.createStatement();

            String s = "select * from enterprise_detail";
            rs = st.executeQuery(s);  // execute query

            while (rs.next()) {

                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3)});

            }

        } catch (SQLException ex) {

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Manage Enterprise button
        MainFrame.p2.setVisible(false);
        MainFrame.p1.setVisible(true);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Manage Enterprise admin button
        MainFrame.p2.setVisible(true);
        MainFrame.p1.setVisible(false);

        updateTable();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

        //location combo box click event
        try {
if(conn == (null)){
            try {
                String url = "jdbc:oracle:thin:@10.0.0.107:1521:xe";
                String user = "SYSTEM";
                String password = "trisha";
                Class.forName("oracle.jdbc.driver.OracleDriver");
                conn = DriverManager.getConnection(url, user, password);
            } catch (Exception e) {
            }}
            st = conn.createStatement();
String s ="";
if(!jComboBox1.getSelectedItem().equals(null) || !jComboBox1.getSelectedItem().equals(""))
            s = "select * from enterprise where location='" + jComboBox1.getSelectedItem() + "'";
else s = "select * from enterprise";
            rs = st.executeQuery(s);  // execute query
            jComboBox2.removeAllItems();

            while (rs.next()) {

                jComboBox2.addItem(rs.getString(1));
            }

        } catch (SQLException ex) {

        }


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
